layout_spectrum: 0.99406
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6878874583635479
  lightness: 0.4955867717508227
  brandStrength: 0.5017921
  brandColors:
    - '#6F91BD'
    - '#4A6478'
    - '#F2E8E0'
    - '#1F1603'
    - '#E0E987'
  rhythmicContrast: 0.7962754666805267
typography_spectrum: 0.43905
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thefarmintheforest
