layout_spectrum: 0.02421263354295625
typography_spectrum: 0.18304711640508162
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.8788988167860794
  lightness: 0.10176330977626662
  saturation: 0.916924839247719
  rhythmicContrast: 0.45703061304958814
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: '1982'
author:
  name: Marloes Engelhart
  email: marloesengelhart@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eef7932f-92a5-4c2e-8cc4-8a3e698489f4.png
name: De Vos in het Bos
url: 'https://thegrid.ai/devosinhetbos'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: "About\_"
    id: 5a1b1df1-9a92-4315-86b8-2f69a351f957
    type: content
  - name: Portfolio
    id: 8683ce45-3784-4750-bf2f-3263cc49c11e
    type: content
  - name: 'Weddings & Events '
    id: 37523d1d-8a4e-4a21-9ff9-597acb3a8c27
    type: content
  - name: 'Family Affairs '
    id: c5416ccd-adf4-498e-835c-65a19d152232
    type: content
  - name: Contact
    id: dd19782e-8437-4268-927c-fff9d72849f2
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'De Vos in het Bos '
content: []
description: Media | Cultuur | Maatschappij
purpose:
  - type: contact
    url: 'mailto:marloesengelhart@gmail.com'
    label: Contact us
  - type: contact
    url: 'tel:0031-611725522'
    label: Call us
