name: thefarmintheforest
favicon: null
layout_spectrum: 0.99406
typography_spectrum: 0.43905
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efd6c2'
    - '#fc715a'
    - '#07a98f'
    - '#ba172a'
    - '#0b090a'
  brandStrength: 0.5017921
  lightness: 0.4955867717508227
  saturation: 0.6878874583635479
  rhythmicContrast: 0.7962754666805267
purpose: []
