title: 'The Farm in the Forest '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6878874583635479
  brandStrength: 0.5
  lightness: 0.4955867717508227
  brandColors:
    - '#17171D'
    - '#B4BDBD'
    - '#FBFCFC'
    - '#FBBF01'
    - '#5C6565'
  rhythmicContrast: 0.7962754666805267
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thefarmintheforest
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4462366
layout_spectrum: 0.5985663
