name: 'The Farm in the Forest '
favicon: null
layout_spectrum: 0.10904
typography_spectrum: 0.4462366
title: 'The Farm in the Forest '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8fa'
    - '#899eb3'
    - '#444341'
    - '#a94738'
    - '#a88066'
  brandStrength: 0.5
  lightness: 0.4955867717508227
  saturation: 0.6878874583635479
  rhythmicContrast: 0.7962754666805267
purpose: []
