name: thefarmintheforest
favicon: null
layout_spectrum: 0.24555
typography_spectrum: 0.43905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1f2'
    - '#040d1e'
    - '#72b96b'
    - '#ff6f00'
    - '#a13600'
  brandStrength: 0.16787517303600907
  lightness: 0.49558677175082266
  saturation: 0.6878874583635479
  rhythmicContrast: 0.7962754666805267
purpose: []
